### ISSUE TITLE
Nothing about monkeybrains jar on maven central repo 

### ISSUE THREAD

**Issue by Likenttt** [garmin/connectiq-android-sdk#1]
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.garmin.connectiq:monkeybrains:1.0.2.

I found nothing when searching on maven central repo. So garmin guys, did you forget to publish your jar?

**Comment by galleitnerflo** [comment]
@Likenttt 
for a quick fix, replace 
    implementation("com.garmin.connectiq:monkeybrains:1.0.2")
with 
    implementation(files("./libs/monkeybrains-sdk-release.aar")) 
This worked for me, as I faced the same issue

**Comment by Likenttt** [comment]
> @Likenttt for a quick fix, replace implementation("com.garmin.connectiq:monkeybrains:1.0.2") with implementation(files("./libs/monkeybrains-sdk-release.aar")) This worked for me, as I faced the same issue

Nice remind. Thanks~
